a=int(input("Enter first number\n"))
b=int(input("Enter second number\n"))
c=int(input("Enter third number\n"))
d=int(input("Enter fourth number\n"))
e=int(input("Enter fifth number\n"))
Average=((a+b+c+d+e)/5)
print("Average:",Average)